#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
  path: /
  controller: App\Controller\IndexController::index

main:
  path: /main
  controller: App\Controller\IndexController::main

# User subsystem
login:
  path: /login
  controller: App\Controller\UsersController::login

register:
  path: /register
  controller: App\Controller\UsersController::register

profile:
  path: /user
  controller: App\Controller\UsersController::index

pending-accounts:
  path: /pending
  controller: App\Controller\UsersController::pending

# end of user subsystem
# inventory subsystem

inventory-show:
  path: /inventory
  controller: App\Controller\InventoryController::index

inventory-item-show:
  path: /inventory/item
  controller: App\Controller\InventoryController::show

inventory-item-edit:
  path: /inventory/item/form
  controller: App\Controller\InventoryController::form

inventory-category-show:
  path: /inventory/category
  controller: App\Controller\InventoryController::category

inventory-status-show:
  path: /inventory/status
  controller: App\Controller\InventoryController::status

inventory-report:
  path: /inventory/report
  controller: App\Controller\InventoryController::report

# end of inventory subsystem
# produkt subsystem

produkt-produkt:
  path: /produkt
  controller: App\Controller\ProduktController::produkt

produkt-tiek:
  path: /produkt
  controller: App\Controller\ProduktController::tiek

produkt-medz_gr:
  path: /produkt
  controller: App\Controller\ProduktController::medz_gr

produkt-ataskaita:
  path: /produkt
  controller: App\Controller\ProduktController::ataskaita

produkt-add_tiek:
  path: /produkt
  controller: App\Controller\ProduktController::add_tiek

produkt-add_medz_gr:
  path: /produkt
  controller: App\Controller\ProduktController::add_medz_gr

produkt-add_produkt:
  path: /produkt
  controller: App\Controller\ProduktController::add_produkt

produkt-add_tiek_produkt:
  path: /produkt
  controller: App\Controller\ProduktController::add_tiek_produkt
# end of produkt subsystem
#order subsystem

orders-payment:
  path: /orders/payment
  controller: App\Controller\OrderController::payment

orders-list:
  path: /orders/list
  controller: App\Controller\OrderController::list

orders-edit:
  path: /orders/edit
  controller: App\Controller\OrderController::edit

#end of order subsystem